# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meni.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# from remen import average_price_bar
import matplotlib  # 导入图表模块
import matplotlib.pyplot as plt  # 导入绘图模块

import matplotlib

matplotlib.use("Qt5Agg")
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure

# 避免中文乱码
matplotlib.rcParams['font.sans-serif'] = ['SimHei']  # 设置字体为SimHei显示中文
matplotlib.rcParams['font.size'] = 14  # 设置整体字体大小
matplotlib.rcParams['axes.unicode_minus'] = False  # 设置正常显示字符，使用rc配置文件来自定义


# 绘制图形
class MyFigure(FigureCanvas):
    def __init__(self, width=5, height=4, dpi=100):
        # 第一步：创建一个创建Figure
        self.fig = Figure(figsize=(width, height), dpi=dpi, facecolor='#87CEFA',
                          edgecolor='#87CEFA')  # facecolor='#87CEFA'整个画布的颜色
        # 第二步：在父类中激活Figure窗口
        super(MyFigure, self).__init__(self.fig)  # 此句必不可少，否则不能显示图形


def average_price_bar():
    y = [100, 200, 50]
    x = ['沙坪坝', '渝北', '江北']

    F = MyFigure(3, 3, 100)
    aexs = F.fig.add_subplot(111)

    aexs.bar(x, y, color='r')  # 绘制条形图，柱子颜色
    # 设置坐标名称
    aexs.set_ylabel("价格", color='b', rotation=0, fontsize=14)  # 字体颜色
    aexs.set_xlabel("地区", color='b', fontsize=14)
    aexs.patch.set_facecolor('#87CEFA')  # 上面相应的颜色
    for x, y in enumerate(y):
        aexs.text(x, y + 1, y, ha='center')

    # 标题文字
    F.fig.suptitle("二手房均价分析", color='b', fontsize=20)
    return F

    # average_price_bar()


# 显示饼图
def pie_chart():
    y = [100, 200, 50]
    x = ['沙坪坝', '渝北', '江北']
    F = MyFigure(3, 3, 100)
    aexs = F.fig.add_subplot(111)
    aexs.pie(y, labels=x, autopct='%1.1f%%', shadow=True, startangle=90)  # 绘制条形图，柱子颜色
    aexs.patch.set_facecolor('#87CEFA')  # 上面相应的颜色
    F.fig.suptitle("各地区销售数量", color='b', fontsize=20)
    return F
