# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import matplotlib  # 导入图表模块
import matplotlib.pyplot as plt  # 导入绘图模块
import chart

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1170, 832)
        MainWindow.setStyleSheet("border-image: url(:/bj/image/背景.jpg);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 10, 411, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("border-image: url(:/bj/image/背景颜色.jpg);\n"
                                 "font: 30pt \"黑体\";\n"
                                 "color: rgb(255, 255, 0);\n"
                                 "")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 70, 1161, 711))
        self.label_2.setStyleSheet("border-image: url(:/bj/image/背景颜色.jpg);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 70, 271, 711))
        self.widget.setStyleSheet("border-image: url();")
        self.widget.setObjectName("widget")
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setGeometry(QtCore.QRect(-10, 90, 271, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.widget)
        self.line_3.setGeometry(QtCore.QRect(-10, 240, 271, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.widget)
        self.line_4.setGeometry(QtCore.QRect(-10, 390, 271, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.widget)
        self.line_5.setGeometry(QtCore.QRect(-10, 570, 271, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 241, 81))
        self.pushButton.setStyleSheet("#pushButton{\n"
                                      "color:rgb(186,186,186);\n"
                                      "font:25pt \"隶书\";\n"
                                      "border:none;\n"
                                      "}\n"
                                      "#pushButton:focus{\n"
                                      "backgroud-color:rgba(255,255,255,0);\n"
                                      "          color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
                                      "stop:0 rgba(167, 0, 0, 255), stop:1 rgba(255, 255, 0, 255));\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 140, 241, 81))
        self.pushButton_2.setStyleSheet("#pushButton_2{\n"
                                        "color:rgb(186,186,186);\n"
                                        "font:25pt \"隶书\";\n"
                                        "border:none;\n"
                                        "}\n"
                                        "#pushButton_2:focus{\n"
                                        "backgroud-color:rgba(255,255,255,0);\n"
                                        "          color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
                                        "stop:0 rgba(167, 0, 0, 255), stop:1 rgba(255, 255, 0, 255));\n"
                                        "}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 280, 241, 81))
        self.pushButton_3.setStyleSheet("#pushButton_3{\n"
                                        "color:rgb(186,186,186);\n"
                                        "font:25pt \"隶书\";\n"
                                        "border:none;\n"
                                        "}\n"
                                        "#pushButton_3:focus{\n"
                                        "backgroud-color:rgba(255,255,255,0);\n"
                                        "          color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
                                        "stop:0 rgba(167, 0, 0, 255), stop:1 rgba(255, 255, 0, 255));\n"
                                        "}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 450, 241, 81))
        self.pushButton_4.setStyleSheet("#pushButton_4{\n"
                                        "color:rgb(186,186,186);\n"
                                        "font:25pt \"隶书\";\n"
                                        "border:none;\n"
                                        "}\n"
                                        "#pushButton_4:focus{\n"
                                        "backgroud-color:rgba(255,255,255,0);\n"
                                        "          color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
                                        "stop:0 rgba(167, 0, 0, 255), stop:1 rgba(255, 255, 0, 255));\n"
                                        "}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 600, 241, 81))
        self.pushButton_5.setStyleSheet("#pushButton_5{\n"
                                        "color:rgb(186,186,186);\n"
                                        "font:25pt \"隶书\";\n"
                                        "border:none;\n"
                                        "}\n"
                                        "#pushButton_5:focus{\n"
                                        "backgroud-color:rgba(255,255,255,0);\n"
                                        "          color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
                                        "stop:0 rgba(167, 0, 0, 255), stop:1 rgba(255, 255, 0, 255));\n"
                                        "}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(262, 70, 16, 711))
        self.line.setStyleSheet("border-image: url();\n"
                                "color: rgb(255, 255, 0);")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(270, 70, 891, 721))
        self.groupBox.setStyleSheet("border-image: url();\n"
                                    "border:none;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(270, 70, 891, 721))
        self.groupBox_2.setStyleSheet("border-image: url();\n"
                                      "border:none;")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1170, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # self.pushButton.clicked.connect(self.average_price_bar)
        QtWidgets.QGridLayout(self.groupBox).addWidget(chart.average_price_bar())
        QtWidgets.QGridLayout(self.groupBox_2).addWidget(chart.pie_chart())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def price_bar(self):
        QtWidgets.QGridLayout(self.groupBox_2)

    def pie_chart(self):
        QtWidgets.QGridLayout(self.groupBox)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "二手房软件"))
        self.pushButton.setText(_translate("MainWindow", "均价分析"))
        self.pushButton_2.setText(_translate("MainWindow", "数量比例"))
        self.pushButton_3.setText(_translate("MainWindow", "装修程度"))
        self.pushButton_4.setText(_translate("MainWindow", "热门户型"))
        self.pushButton_5.setText(_translate("MainWindow", "预测分析"))


import qec_rc
